controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_authentication:
    path: /authentication

gesdinet_jwt_refresh_token:
    path: /refresh